#
#  MLG Rush - created by GrowlyX & puugz (SolexGames)
#
settings:
  server-ip: "nigeria.live.ng"
mongodb:
  url: ""
# List of all arenas
arenas:
  # for debug; keep this here
  test: ""
language:
  primary-color: "GOLD"
  secondary-color: "YELLOW"
