#
#  MLG Rush - created by GrowlyX & puugz (SolexGames)
#
settings:
  # should we enable the npc command
  enable-npcs: true
  # what should the amount of points be for a player to win a match
  winner-point-amount: 5
  # should we enable a 5 second cooldown between bed breaks
  round-cooldown: false
  # should we make the game start countdown 20 seconds instead of 5
  long-match-start: false
  # should we enable spawn protection near beds so players can't
  # place blocks their or the opponent's beds
  spawn-protection: false
mongodb:
  # MongoDB connection URL
  url: ""
# list of all arenas
arenas:
  # for debug; keep this here
  test: ""
language:
  # your highlight color which will show on messages
  primary-color: "GOLD"
  # your primary color which will be used as a secondary background color
  secondary-color: "YELLOW"
locations:
  join-game-npc: ""
