#
#  MLG Rush - created by GrowlyX & puugz (SolexGames)
#
settings:
  # should we enable the npc command
  enable-npcs: true
  # what should the amount of points be for a player to win a match
  winner-point-amount: 5
  # should we enable a 5 second cooldown between bed breaks
  round-cooldown: false
  # should we make the game start countdown 20 seconds instead of 5
  long-match-start: false
  # should we enable spawn protection near beds so players can't
  # place blocks their or the opponent's beds
  spawn-protection: false
mongodb:
  url: ""
  database: ""
language:
  primary-color: "GOLD"
  secondary-color: "YELLOW"
locations:
  spawn: ""
hotbar:
  join-arena:
    slot: 1
    material: COMPASS
    display-name: "&6Join an Arena &7(Right Click)"
#    lore: # (example to add lore to an item)
#      - "&7Right Click to select an arena and play!"
    commands:
      enabled: true
      commands:
        - "[PLAYER] play"
#        - "[CONSOLE] gamemode 1 player" # (example of console commands)
  spectate:
    slot: 2
    material: ENDER_CHEST
    display-name: "&6Spectate a Match &7(Right Click)"
    commands:
      enabled: true
      commands:
        - "[PLAYER] spectate"
  layout:
    slot: 9
    material: BOOK
    display-name: "&6Edit layout &7(Right Click)"
    commands:
      enabled: true
      commands:
        - "[PLAYER] layout"
